### ISSUE TITLE
myFinanceService - Expense tracker 

### ISSUE THREAD

**Issue by tommiAtGit** [tommiAtGit/myDashBoard#10]
I can track and trace my expences based on data and expence category 

- [x] As a myFinanceService I need to have database and required scripts for Expense tracker 

- [x] As a myFinanceService I need to have controller and required CRUD-endpoints for Expense tracker 

- [x] As a myFinanceService I need to have entity and DTO objects for Expense tracker 

- [x] As a myFinanceService I need to have object mapper for Expense tracker  DTO and entity objets
